// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Data;

#nullable disable

namespace LatihanEFCore.DTO.Responses.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905124925_MakeStudentOrganizationOptional")]
    partial class MakeStudentOrganizationOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentActivityPoints", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("IdActivityPoints")
                        .HasColumnType("int");

                    b.HasKey("IdStudent", "IdActivityPoints");

                    b.HasIndex("IdActivityPoints");

                    b.ToTable("StudentActivityPoints", (string)null);
                });

            modelBuilder.Entity("StudentCourses", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("IdCourse")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdStudent", "IdCourse");

                    b.HasIndex("IdCourse");

                    b.ToTable("StudentCourses", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.ActivityPoints", b =>
                {
                    b.Property<int>("IdActivityPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdActivityPoints"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdActivityPoints");

                    b.ToTable("ActivityPoints", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Classroom", b =>
                {
                    b.Property<string>("IdClassroom")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdClassroom");

                    b.ToTable("Classrooms", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", b =>
                {
                    b.Property<string>("IdCourse")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClassroomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassroomIdClassroom")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Hours")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdTeacher")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherIdTeacher")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCourse");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ClassroomIdClassroom");

                    b.HasIndex("IdTeacher");

                    b.HasIndex("TeacherIdTeacher");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", b =>
                {
                    b.Property<int>("IdOrganization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrganization"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("IdTeacher")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdOrganization");

                    b.HasIndex("IdTeacher")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.PublicationTeacher", b =>
                {
                    b.Property<int>("IdPublicationTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPublicationTeacher"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPublicationTeacher");

                    b.HasIndex("TeacherId");

                    b.ToTable("PublicationTeachers", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("IdOrganization")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdOrganization");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTeacher"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("idCourse")
                        .HasColumnType("int");

                    b.HasKey("IdTeacher");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Tuition", b =>
                {
                    b.Property<int>("IdTuition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTuition"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdCourse")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.HasKey("IdTuition");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdStudent");

                    b.ToTable("Tuitions", (string)null);
                });

            modelBuilder.Entity("StudentActivityPoints", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.ActivityPoints", null)
                        .WithMany()
                        .HasForeignKey("IdActivityPoints")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentCourses", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("IdCourse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Classroom", null)
                        .WithMany("Courses")
                        .HasForeignKey("ClassroomIdClassroom");

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("IdTeacher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", null)
                        .WithMany("Courses")
                        .HasForeignKey("TeacherIdTeacher");

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "Teacher")
                        .WithOne("Organization")
                        .HasForeignKey("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", "IdTeacher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.PublicationTeacher", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "IdTeacher")
                        .WithMany("PublicationTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdTeacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", "Organization")
                        .WithMany("Students")
                        .HasForeignKey("IdOrganization")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Tuition", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("IdCourse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", "Student")
                        .WithMany("Tuitions")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Classroom", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", b =>
                {
                    b.Navigation("Tuitions");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Organization")
                        .IsRequired();

                    b.Navigation("PublicationTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
