// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Data;

#nullable disable

namespace LatihanEFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.ActivityPoints", b =>
                {
                    b.Property<int>("IdActivityPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdActivityPoints"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdActivityPoints");

                    b.HasIndex("IdStudent")
                        .IsUnique();

                    b.ToTable("ActivityPoints", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Classroom", b =>
                {
                    b.Property<int>("IdClassroom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdClassroom"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdClassroom");

                    b.ToTable("Classrooms", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", b =>
                {
                    b.Property<string>("IdCourse")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Hours")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCourse");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", b =>
                {
                    b.Property<int>("IdOrganization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrganization"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("IdOrganization");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.PublicationTeacher", b =>
                {
                    b.Property<int>("IdPublicationTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPublicationTeacher"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPublicationTeacher");

                    b.HasIndex("TeacherId");

                    b.ToTable("PublicationTeachers", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("IdStudent");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTeacher"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("IdTeacher");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Tuition", b =>
                {
                    b.Property<int>("IdTuition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTuition"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CourseId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("IdTuition");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Tuitions", (string)null);
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.ActivityPoints", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", null)
                        .WithOne("IdActivityPoints")
                        .HasForeignKey("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.ActivityPoints", "IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "IdTeacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdTeacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", "IdStudent")
                        .WithOne("IdOrganization")
                        .HasForeignKey("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Organization", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "IdTeacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdStudent");

                    b.Navigation("IdTeacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.PublicationTeacher", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Teacher", "IdTeacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdTeacher");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Tuition", b =>
                {
                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Course", "IdCourse")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", "IdStudent")
                        .WithOne("IdTuition")
                        .HasForeignKey("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Tuition", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCourse");

                    b.Navigation("IdStudent");
                });

            modelBuilder.Entity("home.mahindra.RiderProjects.LatihanEFCore.LatihanEFCore.Models.Student", b =>
                {
                    b.Navigation("IdActivityPoints")
                        .IsRequired();

                    b.Navigation("IdOrganization");

                    b.Navigation("IdTuition")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
